[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py loaddata fixtures/initial_data.json && gunicorn DjangoProject.wsgi"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.11"